### ISSUE TITLE
Scheduled Jobs DB unknown error

### ISSUE THREAD

**Issue by madmasa** [lemniscus/osdi-client#18]
Hi,
I have an issue: Finished execution of Action Network Job 2: Batch Sync People with result: Failure, Error message: DB Error: unknown error.

Parameters raw (from db settings): 
sync_profile_id=1
origin=remote,local

Parameters parsed (and passed to API method): 
a:3:{s:7:"version";i:3;s:15:"sync_profile_id";s:1:"1";s:6:"origin";s:12:"remote,local";}

Full message: 
Finished execution of Action Network Job 2: Batch Sync People with result: Failure, Error message: DB Error: unknown error

SyncProfile:
(1) [
  {
    "id": 1,
    "is_default": true,
    "label": "Action Network Sync",
    "entry_point": "https://actionnetwork.org/api/v2/",
    "api_token": "XXXXXXX",
    "classes": null
  }
]

**Comment by highfalutin** [comment]
Hi, please provide me with a way to contact you privately. You can send me a direct message on https://chat.civicrm.org/ -- username noah.
